# Generated by Django 4.2.1 on 2023-05-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_alter_product_image_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="paymente_intent",
        ),
    ]
