# Generated by Django 4.2.1 on 2023-05-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_merchant_id_order_paymente_intent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paymente_intent",
            new_name="payment_intent",
        ),
    ]
