# Generated by Django 4.2.1 on 2023-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_options_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_intent",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
